### ISSUE TITLE
Transferir canais do Slack para o GitHub

### ISSUE THREAD

**Issue by afrassoni** [GAM-DIMNT-CPTEC/Documentos#2]
Transferir determinados canais do Slack para o GitHub, criando um projeto para cada canal. Mover do quadro "Atividades GAM", as tarefas específicas para os projetos correspondentes.

**Comment by CGCT-CPTEC-DIMNT** [comment]
Criação do projeto Assuntos-gerais

- Criação das issues:

     Atualizar documento das atribuições
     Reunião de 18/04/2022 9:00 às 10:40
     Reunião Prática SCANPLOT - 20/04/22
     Apresentação sobre o TRACK
